### ISSUE TITLE
Extend to Handle content: Schemes

### ISSUE THREAD

**Issue by commonsguy** [cketti/SafeContentResolver#1]
The same problem can occur if the third-party app sends over a `content:` `Uri` for the app's own `ContentProvider`.

Given that [`file:` schemes are being targeted for destruction in Android N](https://commonsware.com/blog/2016/03/14/psa-file-scheme-ban-n-developer-preview.html), developers are going to start switching _en masse_ to things like `FileProvider`. Frequently, those are not exported (`FileProvider` doesn't even allow exporting), but use `grantUriPermissions` to make content accessible on a per-request basis. Apps can access their own providers without permission, though, and so we have the same basic issue as `SafeContentResolver` addresses for `file:` schemes. The only saving grace is that, for many apps, less stuff will be accessible by a `ContentProvider`.

For API Level 21+, the same approach that you are using (`Os` and `StructStat`) works for `FileProvider` and for providers that use `ParcelFileDescriptor.createPipe()`. You can use `getContentResolver().openFileDescriptor()` (passing in the `Uri` to `openFileDescriptor()`) and get a `ParcelFileDescriptor` on the stream.

If your JNI code for older devices is pretty much just `Os.fstat()`, that may work as well &mdash; I only have modest C/C++ POSIX experience.

If you'd like, I can take a shot at adding this to `SafeContentResolver`.

**Comment by cketti** [comment]
We don't have to worry about hardlinks with content-URIs. So simply blacklisting all content providers of the app should do the trick.

It would be nicer if there was a way to find out if the sending app has permission to access the content URI. That would also handle cases where being handed a URI to your own content provider is part of a legitimate use case. But I guess there's no way to tell which app sent the Intent.

What do you think of automatic blacklisting of content providers and optional whitelisting of certain content provider authorities?

**Comment by commonsguy** [comment]
I have this itch in the back of my mind that suggests a problem, but the rest of my mind doesn't know what the itch is yammering about. So, I'll round to the nearest whole mind and say your plan sounds fine. :-)

I haven't played with `ProviderInfo`, and so I don't know if [`authority`](http://developer.android.com/reference/android/content/pm/ProviderInfo.html#authority) really will be only a single authority or if it could be [the semicolon-delimited list from `authorities`](http://developer.android.com/guide/topics/manifest/provider-element.html#auth).

> It would be nicer if there was a way to find out if the sending app has permission to access the content URI

Yeah, I don't think there's a way to do that. Heck, even a legitimate holder of the `Uri` does not know if they have access until they try accessing it and go _boom_ when they lack permission.

**Comment by cketti** [comment]
I'm not too happy about the public API and may change it later. But the functionality is there:
https://github.com/cketti/SafeContentResolver/compare/content_provider_support

What do you think?

**Comment by commonsguy** [comment]
If your concern regarding the API is having to pass in the whitelisted authorities, you could go the `<meta-data>` route. Either have a boolean `<meta-data>` element per whitelisted `<provider>`, or have a single application-level `<meta-data>` element pointing to an XML resource that, at present, contains the whitelist. Those have the advantage of not cluttering up the Java, at the cost of not allowing runtime changes to the whitelist.

But otherwise, by Mark I Eyeball, what you have seems fine. Thanks!

**Comment by cketti** [comment]
Thanks for the suggestion. I went with the `<meta-data>` element to whitelist content providers.
