### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by runningcode** [cketti/SafeContentResolver#2]
This will help dependent projects like K-9 Mail drop the jetifier which will improve build speeds.

**Comment by cketti** [comment]
Another instance where including `support-annotations` just for the `@Nullable` and `@NonNull` annotations comes back to bite me :cry:

**Comment by cketti** [comment]
Fixed in [version 1.0.0](https://github.com/cketti/SafeContentResolver/releases/tag/v1.0.0).

**Comment by runningcode** [comment]
Very nice!
